name: CI

permissions: {}

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  push:
    paths-ignore:
      - "**.md"
      - LICENSE

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: alpine:latest
            preinstall: apk add bash coreutils curl git jq
          - container: amazonlinux:latest
            preinstall: dnf -y install git findutils jq
          - container: ubuntu:latest
            preinstall: apt-get -y update && apt-get -y install curl git jq

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Preinstall
        run: ${{ matrix.preinstall }}

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kubecolor --kubecolor-version

  macos:
    runs-on: macos-latest

    steps:
      - name: Preinstall
        run: brew install jq

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: kubecolor --kubecolor-version
